services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      db1:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
        - MYSQL_URL=jdbc:mysql://db:3306/vehicle_booking_rental
        - TZ=Asia/Ho_Chi_Minh
        - REDIS_HOST=redis
        - REDIS_PORT=6379


  db1:
    image: mysql:latest
    restart: always
    volumes:
      - mysql-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=vehicle_booking_rental
      - MYSQL_USER=vehicle_booking_rental
      - MYSQL_PASSWORD=vehicle_booking_rental
    ports:
      - 3308:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "vehicle_booking_rental", "--password=vehicle_booking_rental" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    tty: true
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: sh -cx "redis-server --daemonize yes && redis-cli config set notify-keyspace-events KEA && sleep infinity"
  redisInsight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - 5540:5540
    volumes:
      - redis_insight_volumes_data:/db

volumes:
  mysql-db-data:
  redis-data:
  redis_insight_volumes_data:
