
services:
  server:
    build:
      context: .
      target: development
    ports:
      - 8081:8080
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/bookingcar
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: mysql
    restart: always
    volumes:
      - mysql-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=bookingcar
      - MYSQL_USER=bookingcar
      - MYSQL_PASSWORD=bookingcar
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "bookingcar", "--password=bookingcar"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql-db-data: