package com.pbl6.VehicleBookingRental.user.util.constant;

public enum NotificationTypeEnum {
    NEW_BOOKING,
    CANCELED_BOOKING,
    BOOKING_COMPLETED,
    RECEIVED_REGISTER_PARTNER_FORM,
    APPROVAL_REGISTER_PARTNER_FORM,
    CANCELED_REGISTER_PARTNER_FORM,
    REFUSED_REGISTER_PARTNER_FORM,

}
